using Newtonsoft.Json;
using System;

[Serializable]
public class ScoreEntry
{
	[JsonProperty("id")] public int id;
	[JsonProperty("name")] public string name; // player name
	[JsonProperty("score")] public int score; // score points
	[JsonProperty("timeMs")] public long timeMs; // total time spent in ms at game session
	[JsonProperty("date")] public string date; // seconds minutes hours and day month year

	[JsonProperty("weapon")] public string weapon; // preffered weapon
	[JsonProperty("country")] public string country; // country of player (take from client)
	[JsonProperty("version")] public string version; // Application.Version

	[JsonProperty("deviceId")]
	public string deviceId; // unique device id (take from client)

	[JsonProperty("clientEntryId")]
	public string clientEntryId; // unique entry id generated by client (for upsert)
}
